<div class="row">
	<div class="col-sm-12">
		<div class="row">
			<!-- seção Perfil -->
			<div class="col-sm-3 well" id="profile">
				<section>
					<a href="<?php echo $this->url('wall', array('username' => $profileData->getUsername())); ?>" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>" class="thumbnail">
						<img src="/images/avatar.png" alt="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>" />
					</a>
					<ul>
						<li>
							<h3><i class="icon-user"></i> <?php echo $this->translate('Bio'); ?></h3>
							<p><?php echo $profileData->getBio(); ?></p>
						</li>
						<li>
							<h3><i class="icon-globe"></i> <?php $this->translate('Location'); ?> </h3>
							<p><?php echo $profileData->getLocation(); ?></p>
						</li>
						<li>
							<h3><i class="icon-heart"></i> <?php $this->translate('Gender'); ?> </h3>
							<p><?php echo $profileData->getGenderString(); ?></p>
						</li>
					</ul>
				</section>
			</div>
			<!-- perfil de parede -->
			<div class="col-sm-9" id="wall">
				<section>
					<!-- Perfil de parede córrego principal -->
					<div id="wall-stream">
						<h2><?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?></h2>
					</div>
				</section>
			</div><!-- Fechar perfil de parede -->
		</div>
	</div>
</div>