<div class="row">
	<div class="col-sm-12">
		<div class="row">
			<!-- seção Perfil -->
			<div class="col-sm-3 well" id="profile">
				<section>
					<a href="<?php echo $this->url('wall', array('username' => $profileData->getUsername())); ?>" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>" class="thumbnail">
						<img src="/images/avatar.png" alt="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>" />
					</a>
					<ul>
						<li>
							<h3><i class="icon-user"></i> <?php echo $this->translate('Bio'); ?></h3>
							<p><?php echo $profileData->getBio(); ?></p>
						</li>
						<li>
							<h3><i class="icon-globe"></i> <?php echo $this->translate('Location'); ?></h3>
							<p><?php echo $profileData->getLocation(); ?></p>
						</li>
						<li>
							<h3><i class="icon-heart"></i> <?php echo $this->translate('Gender'); ?></h3>
							<p><?php echo $profileData->getGenderString(); ?></p>
						</li>
					</ul>
				</section>
			</div>
			<!-- perfil de parede -->
			<div class="col-sm-9" id="wall">
				<section>
					<!-- Perfil de parede córrego principal -->
					<div id="wall-stream">
						<h2><?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?></h2>
					</div>
				</section>
				<section>
					<div class="tabbable"><!-- Só exigido para guias esquerda / direita -->
						<ul class="nav nav-tabs">
							<li class="active">
								<a href="#wall-status" data-toggle="tab">
									<i class="icon-pencil"></i>
								</a>
							</li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="wall-status">
								<?php 
									echo $this->partial('forms/text-content-form.phtml', array(
										'form' => $textContentForm
									));
								?>
							</div>
						</div>
					</div>
				</section>
				<section>
					<ul class="post-list">
						<?php foreach($profileData->getFee() as $entry): ?>
								<li class="post"> 
									<section>
										<a href="<?php echo $this->url('wall', array('username' => $profileData->getUsername())); ?>" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>" class="pull-left thumbnail">
											<img src="/images/avatar.png" alt="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>" />
										</a>
										<div class="post-body">
											<h4 class="post-heading">
												<a href="<?php echo $this->url('wall', array('username' => $profileData->getUsername())); ?>" title="<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>">
												<?php printf('%s %s', $profileData->getName(), $profileData->getSurname()); ?>
												</a>
											</h4>
											<?php if($entry instanceOf \Wall\Entity\Status): ?>
														<p><?php echo $entry->getStatus(); ?></p>
										    <?php endif; ?>
										</div>
									</section>
								</li>
						<?php endforeach; ?>
					</ul>
				</section>
			</div>
		</div>
	</div>
</div>